---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - 172.16.1.100 kube-master
        - 172.16.1.101 kube-node1
        - 172.16.1.102 kube-node2
        - 172.16.1.103 registry

    - name: Adiciona usuario suporte
      user:
        name: suporte
        shell: /bin/bash
        password : $1$QbUARykG$p2nthVG8AkDvabKPHwboa1

    - name: Adiciona usuario devops
      user:
        name: devops
        shell: /bin/bash
        password : $1$QbUARykG$p2nthVG8AkDvabKPHwboa1

    - name: Criando o arquivo 98_4linux
      copy:
        src: files/registry/98_4linux
        dest: /etc/sudoers.d
        mode: 0644

    - name: Cria o diretorio auth para o usuario suporte
      file:
        path: /home/suporte/auth
        state: directory
        mode: '0775'

    - name: Cria o diretorio certs para o usuario suporte
      file:
        path: /home/suporte/certs
        state: directory
        mode: '0775'

    - name: Criando o arquivo htpasswd
      copy:
        src: files/htpasswd
        dest: /home/suporte/auth
        mode: 0664

    - name: Criando o arquivo registry.crt
      copy:
        src: files/registry.crt
        dest: /home/suporte/certs
        mode: 0664

    - name: Criando o arquivo registry.key
      copy:
        src: files/registry.key
        dest: /home/suporte/certs
        mode: 0664

    - name: Criando o arquivo docker-compose.yaml
      copy:
        src: files/docker-compose.yaml
        dest: /home/suporte
        mode: 0644

    - name: Definir permissao de acesso da HOME do usuario suporte
      file:
        path: /home/suporte
        owner: suporte 
        group: suporte 
        state: directory
        recurse: yes

    - name: Criando diret贸rio data
      synchronize:
        src: files/data
        dest: /home/suporte

    - name: Definir permissao de acesso do diret贸rio data
      file:
        path: /home/suporte/data
        owner: root 
        group: root 
        state: directory
        recurse: yes

    - name: Criando diret贸rio /opt/data
      file:
        path: /opt/data
        state: directory
        mode: '0775'

    - name: Criando diret贸rio /opt/app
      synchronize:
        src: files/app
        dest: /opt

    - name: Instalando o NFS e DNS Server
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - nfs-kernel-server
        - bind9

    - name: Criando o arquivo exports
      lineinfile:
        path: /etc/exports
        line: "{{ item }}"
      with_items:
        - /opt/data 172.16.1.0/24(rw,no_root_squash)
        - /opt/app 172.16.1.0/24(rw,no_root_squash)

    - name: Reinicia o service do nfs-kernel-server
      systemd:
        state: restarted
        name: nfs-kernel-server

    - name: Criando o arquivo named.conf.local
      copy:
        src: files/named.conf.local
        dest: /etc/bind
        owner: root
        group: bind
        mode: 0644

    - name: Criando o arquivo named.conf.options
      copy:
        src: files/named.conf.options
        dest: /etc/bind
        owner: root
        group: bind
        mode: 0644

    - name: Criando o arquivo 4labs.example
      copy:
        src: files/4labs.example
        dest: /etc/bind
        owner: root
        group: bind
        mode: 0644

    - name: Criando o arquivo 1.16.172.db
      copy:
        src: files/1.16.172.db
        dest: /etc/bind
        owner: root
        group: bind
        mode: 0644

    - name: Reinicia o service do bind9
      systemd:
        state: restarted
        name: bind9
  
    - name: Instala pacotes que permitem que o apt seja usado sobre HTTPS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Adiciona uma chave de assinatura apt para o Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adiciona repositorio apt para versao estavel
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: Instala o Docker e suas dependencias
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Adiciona o usuario suporte no grupo docker
      user:
        name: suporte
        group: docker

    - name: Cria o diretorio registry:5000
      file:
        path: /etc/docker/certs.d/registry:5000
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Criando o arquivo ca.crt
      copy:
        src: files/ca.crt
        dest: /etc/docker/certs.d/registry:5000
        owner: suporte
        group: suporte
        mode: '0644'

    - name: Instala o docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.25.5/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Inicia o Docker Registry atraves do Docker Compose
      command: docker-compose -f /home/suporte/docker-compose.yaml up -d