---
- name: kube-balancer
  box: ubuntu/bionic64
  hostname: kube-balancer
  ipaddress: 172.16.1.150
  memory: 512
  cpus: 1
  provision: provision/ansible/kube-balancer.yaml

- name: kube-multi-master1
  box: ubuntu/bionic64
  hostname: kube-multi-master1
  ipaddress: 172.16.1.151
  memory: 2048
  cpus: 1
  provision: provision/ansible/kube-multi-master1.yaml

- name: kube-multi-master2
  box: ubuntu/bionic64
  hostname: kube-multi-master2
  ipaddress: 172.16.1.152
  memory: 2048
  cpus: 1
  provision: provision/ansible/kube-multi-master2.yaml

- name: kube-multi-master3
  box: ubuntu/bionic64
  hostname: kube-multi-master3
  ipaddress: 172.16.1.153
  memory: 2048
  cpus: 1
  provision: provision/ansible/kube-multi-master3.yaml
